### ISSUE TITLE
Clean up dev permissions and create offboarding document

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/Sustainment-Team#13]
**Describe the task**
Clean up access permissions for Devs that have left sustainment

**Purpose**
With the devs having left Sustainment, they no longer require access to repos/applications. [Under Principle of Least Privelege](https://www.paloaltonetworks.com/cyberpedia/what-is-the-principle-of-least-privilege) These devs should no longer have access to things no longer applicable to their position. 

additionally, this 

**Acceptance Criteria**
- [x] OpenShift Access
- [x] SSO Access
- [x] GitHub Teams Access
- [ ] MS Teams access? (as there is not sensitive information here, individual users can unsubscribe themselves as desired)
- [x] Offboarding document to ensure devs leaving have permissions reduced appropriately
- [x] offboarding docs include what to do for senior devs vs junior dves

**Additional context**
- Add any other context about the task here.
- Or here
- 7068-ad is shared with namespace with the range team

**Comment by fergmac** [comment]
Offboarding document additions:

- openshift registry app team lead status: https://registry.developer.gov.bc.ca/private-cloud/products/all
- sonarcloud (static analysis)
      - https://sonarcloud.io/project/configuration?id=bcgov-gwells_backend
      - https://sonarcloud.io/project/configuration?id=bcgov-gwells_backend

**Comment by acatchpole** [comment]
Gone through all (known) former Sustainment Team members and removed SSO (keycloak) access to all Sustainment Team projects and related Keycloak teams.

**Comment by acatchpole** [comment]
In Openshift, all former Devs have been removed as admins in all namespaces except for 

![Image](https://github.com/bcgov/Sustainment-Team/assets/113044739/c0007d52-1cd3-4aa2-b3af-9ed4f88d94d6)

in GWELLS and NMP. Likely something in the Product Registry that is making it so I can't remove it.

Also, I have not touched the Inspect namespaces at this time due to the mix of teams needing access to it.

**Comment by acatchpole** [comment]
Gone through Openshift and removed admin users for everyone who is not current Sustainment Team, an external currently working in that repo, or a Service Owner for that project.

Also had the Project Registry updated to remove old secondary technical leads.

**Comment by acatchpole** [comment]
Gone through the github repos and updated access as same as openshift. A few unknown names were left as contributors but had access lowered to "Read". All current Sustainment members also had their individual users access removed. Most access should now be done through the Sustainment-Team and Sustainment-Team-Admin groups.
