### ISSUE TITLE
Offboard LocalNewsTV from sustainment Apps

### ISSUE THREAD

**Issue by jakemorr** [bcgov/Sustainment-Team#16]
**Describe the task**
Offboard ML from susteam repos, and follow offboarding checklist

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] offboarding checklist is complete
- [x] we give LocalNewsTV an E card

**Additional context**
- Don't remove from Capstone Students project or their OpenShift namespace (`b4cd74`)
    - Can remove from the namespace once their project completes :) 
- Do not remove from `7068ad` namespace (Shared with Range team)

**Comment by fergmac** [comment]
[Offboarding Doc](https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/Developer+Offboarding+Notes)

**Comment by acatchpole** [comment]
Removed keycloak access to all sustainment apps except Inspect and InspectBC. NOT removed from Sustainment Team Keycloak team because i am unsure if needed for Inspect access

**Comment by acatchpole** [comment]
Removed from all Sustainment Team Openshift namespaces (except Inspect and Capstone). Removed from all github except Invasices/Inspect/Lucy. Removed from Sustainment Team groups.
