### ISSUE TITLE
Obtain new project namespace in OpenShift

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/Sustainment-Team#4]
**Describe the task**
Contact platform services about obtaining a new project namespace in OpenShift for Sustainment team to experiment in

**Purpose**
Project namespaces are resource limited, so it's harder to do experimentation with openshift because of these limits.
With the conversations around updating pipelines with Tekton and GitHub Actions, we need a safe space to ensure our projects can be deploying properly before we retire the Jenkins pipeline. By having a new project space we don't have to worry about about hitting resource quotas in our application

**Acceptance Criteria**
- [ ] Contact platform services to obtain project namespace

**Additional context**
After pipeline work is complete, we would be left with an OpenShift playground to experiment with app rebuilds, or have room to make pipelines for developers to obtain more OpenShift experience in.

**Comment by LocalNewsTV** [comment]
Request submitted to Platform Services to obtain new namespace

**Comment by LolandaE** [comment]
Request is pending with OCIO
